#include "testing.h"
#include "tokstream.h"

// INFO: this test is generated by AI
DECLARE_TEST(tokstream)
{
    /*
     * Keywords, identifiers and integer literals.
     */
    {
        const char *text =
            "int void return if else while for "
            "foo _foo foo123 _123 "
            "0 1 42 1234567890";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_INT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_VOID));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_RETURN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_IF));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_ELSE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_WHILE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_FOR));

        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Delimiters and punctuation.
     */
    {
        const char *text =
            "( ) "
            "{ } "
            "[ ] "
            "; , "
            ". "
            "? : "
            "...";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_LPAREN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_RPAREN));

        TEST_ASSERT_A(tok_expect(TOKTYPE_LBRACE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_RBRACE));

        TEST_ASSERT_A(tok_expect(TOKTYPE_LBRACKET));
        TEST_ASSERT_A(tok_expect(TOKTYPE_RBRACKET));

        TEST_ASSERT_A(tok_expect(TOKTYPE_SEMICOLON));
        TEST_ASSERT_A(tok_expect(TOKTYPE_COMMA));

        TEST_ASSERT_A(tok_expect(TOKTYPE_DOT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_QUESTION));
        TEST_ASSERT_A(tok_expect(TOKTYPE_COLON));

        TEST_ASSERT_A(tok_expect(TOKTYPE_ELLIPSIS));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Basic arithmetic operators.
     */
    {
        const char *text =
            "+ - * / % "
            "++ --";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_PLUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MINUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_STAR));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SLASH));
        TEST_ASSERT_A(tok_expect(TOKTYPE_PERCENT));

        TEST_ASSERT_A(tok_expect(TOKTYPE_PLUS_PLUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MINUS_MINUS));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Assignment operators.
     */
    {
        const char *text =
            "= "
            "*= /= %= "
            "+= -= "
            "<<= >>= "
            "&= ^= |=";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL));

        TEST_ASSERT_A(tok_expect(TOKTYPE_MUL_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_DIV_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MOD_ASSIGN));

        TEST_ASSERT_A(tok_expect(TOKTYPE_ADD_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SUB_ASSIGN));

        TEST_ASSERT_A(tok_expect(TOKTYPE_LEFT_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_RIGHT_ASSIGN));

        TEST_ASSERT_A(tok_expect(TOKTYPE_AND_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_XOR_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_OR_ASSIGN));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Comparison and logical operators.
     */
    {
        const char *text =
            "== != "
            "< > <= >= "
            "&& || "
            "! "
            "& | ^ ~ "
            "<< >>";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_NOT_EQUAL));

        TEST_ASSERT_A(tok_expect(TOKTYPE_LESS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_GREATER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_LESS_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_GREATER_EQUAL));

        TEST_ASSERT_A(tok_expect(TOKTYPE_AND_AND));
        TEST_ASSERT_A(tok_expect(TOKTYPE_OR_OR));

        TEST_ASSERT_A(tok_expect(TOKTYPE_BANG));

        TEST_ASSERT_A(tok_expect(TOKTYPE_AMPERSAND));
        TEST_ASSERT_A(tok_expect(TOKTYPE_PIPE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_CARET));
        TEST_ASSERT_A(tok_expect(TOKTYPE_TILDE));

        TEST_ASSERT_A(tok_expect(TOKTYPE_SHIFT_LEFT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SHIFT_RIGHT));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Arrow operator.
     */
    {
        const char *text = "->";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_ARROW));
        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Operators without whitespace. This is important for maximal-munch
     * / longest-token matching.
     */
    {
        const char *text =
            "a+b-c*d/e%f"
            "a++b--c"
            "a==b!=c<=d>=e"
            "a&&b||c"
            "a<<b>>c"
            "a+=b-=c*=d/=e%=f"
            "a<<=b>>=c"
            "a&=b^=c|=d"
            "a->b"
            "...";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_PLUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MINUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_STAR));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SLASH));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_PERCENT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_PLUS_PLUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MINUS_MINUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_NOT_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_LESS_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_GREATER_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_AND_AND));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_OR_OR));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_SHIFT_LEFT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SHIFT_RIGHT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_ADD_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SUB_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MUL_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_DIV_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MOD_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_LEFT_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_RIGHT_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_AND_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_XOR_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_OR_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_ARROW));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_ELLIPSIS));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Every token surrounded by arbitrary whitespace.
     */
    {
        const char *text =
            " \t\n\r"
            "int \t void\n return\r"
            "if else while for"
            " ( ) { } [ ] ; , . -> ? :"
            " + - * / % ++ --"
            " = *= /= %= += -= <<= >>="
            " &= ^= |="
            " == != < > <= >="
            " && || ! & | ^ ~ << >> ..."
            "\n\t ";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_INT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_VOID));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_RETURN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_IF));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_ELSE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_WHILE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_KW_FOR));

        TEST_ASSERT_A(tok_expect(TOKTYPE_LPAREN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_RPAREN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_LBRACE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_RBRACE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_LBRACKET));
        TEST_ASSERT_A(tok_expect(TOKTYPE_RBRACKET));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SEMICOLON));
        TEST_ASSERT_A(tok_expect(TOKTYPE_COMMA));
        TEST_ASSERT_A(tok_expect(TOKTYPE_DOT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_ARROW));
        TEST_ASSERT_A(tok_expect(TOKTYPE_QUESTION));
        TEST_ASSERT_A(tok_expect(TOKTYPE_COLON));

        TEST_ASSERT_A(tok_expect(TOKTYPE_PLUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MINUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_STAR));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SLASH));
        TEST_ASSERT_A(tok_expect(TOKTYPE_PERCENT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_PLUS_PLUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MINUS_MINUS));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MUL_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_DIV_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MOD_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_ADD_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SUB_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_LEFT_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_RIGHT_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_AND_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_XOR_ASSIGN));
        TEST_ASSERT_A(tok_expect(TOKTYPE_OR_ASSIGN));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_NOT_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_LESS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_GREATER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_LESS_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_GREATER_EQUAL));

        TEST_ASSERT_A(tok_expect(TOKTYPE_AND_AND));
        TEST_ASSERT_A(tok_expect(TOKTYPE_OR_OR));
        TEST_ASSERT_A(tok_expect(TOKTYPE_BANG));
        TEST_ASSERT_A(tok_expect(TOKTYPE_AMPERSAND));
        TEST_ASSERT_A(tok_expect(TOKTYPE_PIPE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_CARET));
        TEST_ASSERT_A(tok_expect(TOKTYPE_TILDE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SHIFT_LEFT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_SHIFT_RIGHT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_ELLIPSIS));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Keyword boundaries: keywords must only be recognized when the
     * complete identifier is the keyword.
     */
    {
        const char *text =
            "integer "
            "voidptr "
            "return_value "
            "iffy "
            "elsewhere "
            "while_loop "
            "for_each";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Identifier edge cases.
     */
    {
        const char *text =
            "_ "
            "__ "
            "_foo "
            "foo_ "
            "foo__bar "
            "a1 "
            "a123 "
            "_123 "
            "abcdefghijklmnopqrstuvwxyz "
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_IDENTIFIER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Integer literal edge cases.
     *
     * Keep these limited to syntax that the lexer is expected to support.
     * If only decimal literals are supported, malformed/alternate bases
     * should instead be tested as INVALID.
     */
    {
        const char *text =
            "0 "
            "1 "
            "9 "
            "10 "
            "42 "
            "0000 "
            "000123 "
            "2147483647 "
            "2147483648";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INTLIT));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * EOF behavior.
     */
    {
        const char *text = "";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Invalid characters.
     *
     * These should produce TOKTYPE_INVALID if that is the lexer contract.
     */
    {
        const char *text =
            "@ "
            "# "
            "$ "
            "\\ "
            "\" "
            "'";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_INVALID));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INVALID));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INVALID));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INVALID));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INVALID));
        TEST_ASSERT_A(tok_expect(TOKTYPE_INVALID));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    /*
     * Near-miss operators. These are useful for catching accidental
     * longest-match bugs.
     */
    {
        const char *text =
            "+ + "
            "- - "
            "< < "
            "> > "
            "= = "
            "! = "
            "& & "
            "| | "
            "< < = "
            "> > = "
            ". . .";

        init_errors("[test_lexer]", text);
        init_lexer();
        tokstream_init(text);

        TEST_ASSERT_A(tok_expect(TOKTYPE_PLUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_PLUS));

        TEST_ASSERT_A(tok_expect(TOKTYPE_MINUS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_MINUS));

        TEST_ASSERT_A(tok_expect(TOKTYPE_LESS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_LESS));

        TEST_ASSERT_A(tok_expect(TOKTYPE_GREATER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_GREATER));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL));
        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL));

        TEST_ASSERT_A(tok_expect(TOKTYPE_BANG));
        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL));

        TEST_ASSERT_A(tok_expect(TOKTYPE_AMPERSAND));
        TEST_ASSERT_A(tok_expect(TOKTYPE_AMPERSAND));

        TEST_ASSERT_A(tok_expect(TOKTYPE_PIPE));
        TEST_ASSERT_A(tok_expect(TOKTYPE_PIPE));

        TEST_ASSERT_A(tok_expect(TOKTYPE_LESS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_LESS));
        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL));

        TEST_ASSERT_A(tok_expect(TOKTYPE_GREATER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_GREATER));
        TEST_ASSERT_A(tok_expect(TOKTYPE_EQUAL));

        TEST_ASSERT_A(tok_expect(TOKTYPE_DOT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_DOT));
        TEST_ASSERT_A(tok_expect(TOKTYPE_DOT));

        TEST_ASSERT_A(tok_expect(TOKTYPE_EOF));
    }

    TEST_SUCCESS();
}
